/**
 * Metric alias map (DD-17; provisional until the Phase 2 golden tests). Loose labels such as
 * "sales" are safe only because extraction prefers the primary statement's row (extract.ts). Row labels are
 * normalized (lowercase, footnote markers and trailing colons removed) and matched exactly,
 * in priority order: within a filing, the first alias that yields a value wins, so a precise
 * label ("total net sales") beats a looser one ("revenues").
 */
export const METRICS = [
  'revenue',
  'gross_profit',
  'operating_income',
  'net_income',
  'cash_and_equivalents',
  'total_debt',
  'capital_expenditures',
  'operating_cash_flow',
] as const;
export type Metric = (typeof METRICS)[number];

export const METRIC_LABELS: Record<Metric, string> = {
  revenue: 'Revenue',
  gross_profit: 'Gross margin',
  operating_income: 'Operating income',
  net_income: 'Net income',
  cash_and_equivalents: 'Cash and cash equivalents',
  total_debt: 'Total debt',
  capital_expenditures: 'Capital spending',
  operating_cash_flow: 'Operating cash flow',
};

/** Point-in-time balances; everything else is a flow over a period. */
export const INSTANT_METRICS: ReadonlySet<Metric> = new Set(['cash_and_equivalents', 'total_debt']);

type Alias = string | RegExp;

export const METRIC_ALIASES: Record<Metric, readonly Alias[]> = {
  revenue: [
    'total net sales',
    'total revenues',
    'total revenue',
    'total net revenues',
    'total net revenue',
    'total revenue, net of interest expense',
    'net sales',
    'net revenues',
    'net revenue',
    'net operating revenues',
    'revenues',
    'revenue',
    'sales to customers',
    'sales and other operating revenue',
    'sales and other operating revenues',
    'total sales',
    'total operating revenues',
    'total operating revenue',
    'total sales and revenues',
    'total net sales and revenues',
    'total revenues net of interest expense',
    'net sales and revenues',
    'sales',
  ],
  gross_profit: ['gross margin', 'total gross margin', 'gross profit'],
  operating_income: ['operating income', 'operating income (loss)', 'total operating income', 'income from operations', 'operating profit'],
  net_income: [
    /^net (?:income|earnings)(?: \(loss\))? attributable to (?!noncontrolling|non-controlling|redeemable)[a-z0-9 .,&'()-]+$/,
    'net income',
    'net earnings',
    'net income (loss)',
    'net earnings (loss)',
  ],
  cash_and_equivalents: ['cash and cash equivalents', 'cash and equivalents'],
  total_debt: ['total debt', 'total borrowings', 'total term debt'],
  capital_expenditures: [
    'payments for acquisition of property, plant and equipment',
    'purchases of property and equipment',
    'purchases of property, plant and equipment',
    'additions to property and equipment',
    'additions to property, plant and equipment',
    'capital expenditures',
    'purchases related to property and equipment and intangible assets',
    'purchases of property and equipment and intangible assets',
  ],
  operating_cash_flow: [
    'cash generated by operating activities',
    'net cash provided by operating activities',
    'net cash provided by (used in) operating activities',
    'net cash from operations',
    'net cash from operating activities',
    'cash provided by operating activities',
    'net cash flows from operating activities',
  ],
};

/** The metric a normalized row label names, and the alias's priority (lower wins). */
export function matchMetric(label: string): { metric: Metric; priority: number } | null {
  for (const metric of METRICS) {
    const aliases = METRIC_ALIASES[metric];
    for (let p = 0; p < aliases.length; p++) {
      const a = aliases[p]!;
      if (typeof a === 'string' ? a === label : a.test(label)) return { metric, priority: p };
    }
  }
  return null;
}
