/**
 * Regenerates `services/api/src/session/cloudfront-ranges.ts`, the static list of AWS CloudFront
 * address ranges the api uses to decide whether a request reached API Gateway through CloudFront
 * (Amplify's `/api/<*>` rewrite), and so whether the viewer hop of `X-Forwarded-For` can be trusted
 * (assumptions D12). Services CLOUDFRONT and CLOUDFRONT_ORIGIN_FACING, IPv4 and IPv6, from AWS's
 * published ip-ranges.json; the file records its `syncToken` and `createDate`.
 *
 * A stale list is fail-safe: an address it lacks keys on `sourceIp`, as before Phase 8.
 *
 *   pnpm fixtures:cloudfront                 (a read-only GET of the public JSON; no AWS account)
 *   pnpm fixtures:cloudfront --from <file>   (a saved copy instead)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT, fail } from '../lib/common';

const URL_ = 'https://ip-ranges.amazonaws.com/ip-ranges.json';
const SERVICES = ['CLOUDFRONT', 'CLOUDFRONT_ORIGIN_FACING'] as const;
const OUT = join(ROOT, 'services/api/src/session/cloudfront-ranges.ts');

interface IpRanges {
  syncToken: string;
  createDate: string;
  prefixes: Array<{ ip_prefix: string; service: string }>;
  ipv6_prefixes: Array<{ ipv6_prefix: string; service: string }>;
}

const fromIdx = process.argv.indexOf('--from');
const raw = fromIdx > 0 ? readFileSync(process.argv[fromIdx + 1] ?? fail('--from needs a file'), 'utf8') : await (await fetch(URL_)).text();
const data = JSON.parse(raw) as IpRanges;
if (!data.syncToken || !Array.isArray(data.prefixes) || !Array.isArray(data.ipv6_prefixes)) fail('unexpected ip-ranges.json shape');
const wanted = (service: string) => (SERVICES as readonly string[]).includes(service);
const ipv4 = [...new Set(data.prefixes.filter((p) => wanted(p.service)).map((p) => p.ip_prefix))].sort();
const ipv6 = [...new Set(data.ipv6_prefixes.filter((p) => wanted(p.service)).map((p) => p.ipv6_prefix))].sort();
if (ipv4.length < 50 || ipv6.length < 10) fail(`suspiciously few ranges: ${ipv4.length} IPv4, ${ipv6.length} IPv6`);

const list = (xs: string[]) => xs.map((x) => `    '${x}',`).join('\n');
writeFileSync(
  OUT,
  `// GENERATED by \`pnpm fixtures:cloudfront\` (scripts/fixtures/build-cloudfront-ranges.ts). Do not edit by hand.
// Source: ${URL_}, services ${SERVICES.join(' and ')} (assumptions D12).

export const CLOUDFRONT_RANGES = {
  source: '${URL_}',
  syncToken: '${data.syncToken}',
  createDate: '${data.createDate}',
  services: ${JSON.stringify(SERVICES).replace(/"/g, "'").replace(/,/g, ', ')},
  ipv4: [
${list(ipv4)}
  ],
  ipv6: [
${list(ipv6)}
  ],
} as const;
`,
);
console.log(`wrote ${OUT}: ${ipv4.length} IPv4 and ${ipv6.length} IPv6 ranges (syncToken ${data.syncToken}, createDate ${data.createDate})`);
