/**
 * Hand-labeled ground truth for the signal-quality evaluation (risk-factor heading changes and
 * emphasis changes between consecutive 10-Ks of AAPL, MSFT and NVDA).
 *
 * Who and how: hand-labeled by a Claude agent reading the processed Item 1A and MD&A text on
 * 2026-10-01 (`.index/work/processed/<documentId>.json`, `text.slice(start, end)` of the sections
 * with kind "risk_factors" and "mda"). The labeler did not look at any detector code under
 * packages/rag/src/signals, so these labels are independent of it.
 *
 * Headings (HEADINGS_BY_DOCUMENT, FY2023 and FY2024): every paragraph and run-in sentence of each
 * Item 1A was read, following the conventions of packages/corpus/src/testing/risk-headings-golden.ts
 * (whose FY2025 lists are reused verbatim as the later headings of the FY2024→FY2025 pairs):
 * - A heading is the sentence that opens one risk and is followed by that risk's body. Sentences
 *   that continue the previous risk are body, even as one-sentence paragraphs. Group titles
 *   ("Macroeconomic and Industry Risks", "OPERATIONAL RISKS") are not headings.
 * - AAPL: "Changes or additions to the Company’s supply chain…" (a standalone paragraph in FY2023,
 *   the last outsourcing paragraph in FY2024) and "Regulatory changes and other actions…" (FY2024)
 *   are body. The FY2023 first heading also appears quoted in a later body sentence; the first
 *   occurrence is the heading.
 * - MSFT: run-in headings. Italic subheads ("Security of our information technology") and
 *   elaborating paragraphs ("Competition law regulatory actions and court decisions…",
 *   "Increasing trade laws…", "Our investment in gaining insights from data…", "How these laws and
 *   regulations apply…", "Abrupt political change…", the climate-change paragraph, "Our AI systems
 *   offer users powerful tools…") are body. "If our goodwill or amortizable intangible assets become
 *   impaired…" is a run-in heading in FY2023 and FY2024 (in FY2025 it is one sentence inside the
 *   acquisitions risk). "We are subject to evolving sustainability regulatory requirements…" is a
 *   heading in FY2024.
 * - NVDA: each heading is the body-section sentence matching a "Risk Factors Summary" bullet
 *   (FY2023: 25 bullets, FY2024: 24). Prefixes are matched in the body, after the summary.
 * Every prefix (and every FY2025 golden prefix used here) was verified programmatically to be an
 * exact substring of its filing's Item 1A, in document order, with the text's curly apostrophes.
 *
 * Pairing (laterHeadings / removed): each later heading points to the earlier heading discussing
 * the same risk; rewording, broadening or narrowing is still the same risk (explained in `note`).
 * `earlier: null` only when the earlier Item 1A had no risk factor covering it, checked against the
 * earlier body text, not only headings; a topic that was a passing mention in another risk's body
 * and became its own risk factor is new with a "Promoted from body" note (MSFT FY2024
 * sustainability). Merges: when several earlier risks were folded into one later risk, the later
 * heading points to the closest earlier heading and the note lists the others; folded headings are
 * NOT listed in `removed`, which holds only risks whose content disappeared (AAPL FY2025 retail
 * stores, NVDA FY2024 COVID-19, NVDA FY2025 indebtedness).
 *
 * Emphasis: per pair, Item 1A categories (regulatory, competition, supply_chain, cybersecurity,
 * litigation, geographic_concentration, customer_concentration, liquidity_debt) and MD&A
 * management-outlook topics (mda_demand, mda_investment = investment/capital spending,
 * mda_headwinds). Judged from a sentence-level diff of the two sections plus per-risk character
 * counts; 'expanded'/'reduced' only when the change is material and an analyst would notice it,
 * otherwise 'similar'. Ambiguous calls and how they were settled:
 * - Content that spans categories is counted once: AAPL tariff text under geographic_concentration
 *   (not supply_chain); AAPL FY2024 U.S. antitrust suits and NVDA/MSFT export controls under
 *   regulatory (not litigation or geographic_concentration).
 * - MSFT FY2024→FY2025 regulatory is 'similar': five risk factors were merged and trimmed (fewer
 *   characters) but new AI, export-control/tariff and cybersecurity-regulation content was added;
 *   the change is a restructuring, not a de-emphasis.
 * - MSFT FY2023→FY2024 litigation is 'expanded' on new disclosed exposures spread across risks
 *   (FTC/Activision, AI copyright claims, IRS NOPAs of $28.9B), although the claims-and-lawsuits
 *   risk itself barely changed.
 * - Mixed MD&A changes (one headwind removed, another added) are 'similar'.
 */

export interface HeadingPairLabel {
  later: string;
  earlier: string | null;
  note?: string;
}

export interface FilingPairLabels {
  ticker: string;
  earlierDocumentId: string;
  earlierFiscalLabel: string;
  laterDocumentId: string;
  laterFiscalLabel: string;
  /** One entry per heading of the later filing. earlier=null means genuinely new. */
  laterHeadings: HeadingPairLabel[];
  /** Prefixes of earlier headings with no counterpart in the later filing (genuinely removed). */
  removed: string[];
  emphasis: Record<string, { label: 'expanded' | 'reduced' | 'similar'; why: string }>;
}

/** FY2023 and FY2024 Item 1A heading prefixes (FY2025 lists live in packages/corpus/src/testing/risk-headings-golden.ts). */
export const HEADINGS_BY_DOCUMENT: Record<string, readonly string[]> = {
  'AAPL_10K_2023Q3_2023-11-03': [
    'The Company’s operations and performance depend significantly on global and regional economic conditions',
    'The Company’s business can be impacted by political events, trade and other international disputes, war, terrorism',
    'Global markets for the Company’s products and services are highly competitive',
    'To remain competitive and stimulate customer demand, the Company must successfully manage frequent introductions',
    'The Company depends on component and product manufacturing and logistical services',
    'Future operating results depend upon the Company’s ability to obtain components',
    'The Company’s products and services may be affected from time to time by design and manufacturing defects',
    'The Company is exposed to the risk of write-downs on the value of its inventory',
    'The Company relies on access to third-party intellectual property',
    'The Company’s future performance depends in part on support from third-party software developers.',
    'Failure to obtain or create digital content that appeals to the Company’s customers',
    'The Company’s success depends largely on the talents and efforts of its team members',
    'The Company depends on the performance of carriers, wholesalers, retailers and other resellers.',
    'The Company’s business and reputation are impacted by information technology system failures',
    'Losses or unauthorized access to or releases of confidential information',
    'Investment in new business strategies and acquisitions could disrupt',
    'The Company’s retail stores are subject to numerous risks and uncertainties.',
    'The Company’s business, results of operations and financial condition could be adversely impacted by unfavorable results of legal proceedings',
    'The Company is subject to complex and changing laws and regulations worldwide',
    'Expectations relating to environmental, social and governance considerations',
    'The technology industry, including, in some instances, the Company, is subject to intense media, political and regulatory scrutiny',
    'The Company’s business is subject to a variety of U.S. and international laws, rules, policies and other obligations',
    'The Company expects its quarterly net sales and results of operations to fluctuate.',
    'The Company’s financial performance is subject to risks associated with changes in the value of the U.S. dollar',
    'The Company is exposed to credit risk and fluctuations in the values of its investment portfolio.',
    'The Company is exposed to credit risk on its trade accounts receivable',
    'The Company is subject to changes in tax rates',
    'The price of the Company’s stock is subject to volatility.',
  ],
  'AAPL_10K_2024Q3_2024-11-01': [
    'The Company’s operations and performance depend significantly on global and regional economic conditions',
    'The Company’s business can be impacted by political events, trade and other international disputes, geopolitical tensions',
    'Global markets for the Company’s products and services are highly competitive',
    'To remain competitive and stimulate customer demand, the Company must successfully manage frequent introductions',
    'The Company depends on component and product manufacturing and logistical services',
    'Future operating results depend upon the Company’s ability to obtain components',
    'The Company’s products and services may be affected from time to time by design and manufacturing defects',
    'The Company is exposed to the risk of write-downs on the value of its inventory',
    'The Company relies on access to third-party intellectual property',
    'The Company’s future performance depends in part on support from third-party software developers.',
    'Failure to obtain or create digital content that appeals to the Company’s customers',
    'The Company’s success depends largely on the talents and efforts of its team members',
    'The Company depends on the performance of carriers, wholesalers, retailers and other resellers.',
    'The Company’s business and reputation are impacted by information technology system failures',
    'Losses or unauthorized access to or releases of confidential information',
    'Investment in new business strategies and acquisitions could disrupt',
    'The Company’s retail stores are subject to numerous risks and uncertainties.',
    'The Company’s business, results of operations and financial condition could be adversely impacted by unfavorable results of legal proceedings',
    'The Company is subject to complex and changing laws and regulations worldwide',
    'Expectations relating to environmental, social and governance considerations',
    'The technology industry, including, in some instances, the Company, is subject to intense media, political and regulatory scrutiny',
    'The Company’s business is subject to a variety of U.S. and international laws, rules, policies and other obligations',
    'The Company expects its quarterly net sales and results of operations to fluctuate.',
    'The Company’s financial performance is subject to risks associated with changes in the value of the U.S. dollar',
    'The Company is exposed to credit risk and fluctuations in the values of its investment portfolio.',
    'The Company is exposed to credit risk on its trade accounts receivable',
    'The Company is subject to changes in tax rates',
    'The price of the Company’s stock is subject to volatility.',
  ],
  'MSFT_10K_2023Q2_2023-07-27': [
    'We face intense competition across all markets for our products and services, which may lead to lower revenue',
    'Our increasing focus on cloud-based services presents execution and competitive risks.',
    'We make significant investments in products and services that may not achieve expected returns.',
    'Acquisitions, joint ventures, and strategic alliances may have an adverse effect on our business.',
    'If our goodwill or amortizable intangible assets become impaired',
    'Cyberattacks and security vulnerabilities could lead to reduced revenue',
    'Disclosure and misuse of personal data could result in liability and harm our reputation.',
    'We may not be able to protect information in our products and services from use by others.',
    'Abuse of our platforms may harm our reputation or user engagement.',
    'The development of the IoT presents security, privacy, and execution risks.',
    'Issues in the development and use of AI may result in reputational or competitive harm or liability.',
    'We may have excessive outages, data losses, and disruptions of our online services',
    'We may experience quality or supply problems.',
    'Government litigation and regulatory activity relating to competition rules may limit how we design and market our products.',
    'Laws and regulations relating to anti-corruption and trade could result in increased costs',
    'Laws and regulations relating to the handling of personal data may impede the adoption of our services',
    'Existing and increasing legal and regulatory requirements could adversely affect our results of operations.',
    'We have claims and lawsuits against us that may result in adverse outcomes.',
    'Our business with government customers may present additional uncertainties.',
    'We may have additional tax liabilities.',
    'We face risks related to the protection and utilization of our intellectual property',
    'Third parties may claim that we infringe their intellectual property.',
    'If our reputation or our brands are damaged, our business and operating results may be harmed.',
    'Adverse economic or market conditions may harm our business.',
    'Catastrophic events or geopolitical conditions may disrupt our business.',
    'The occurrence of regional epidemics or a global pandemic, such as COVID-19',
    'Our global business exposes us to operational and economic risks.',
    'Our business depends on our ability to attract and retain talented employees.',
  ],
  'MSFT_10K_2024Q2_2024-07-30': [
    'We face intense competition across all markets for our products and services, which may adversely affect our results of operations.',
    'Our focus on cloud-based and AI services presents execution and competitive risks.',
    'We make significant investments in products and services that may not achieve expected returns.',
    'Acquisitions, joint ventures, and strategic alliances may have an adverse effect on our business.',
    'If our goodwill or amortizable intangible assets become impaired',
    'Cyberattacks and security vulnerabilities could lead to reduced revenue',
    'Disclosure and misuse of personal data could result in liability and harm our reputation.',
    'We may not be able to protect information in our products and services from use by others.',
    'Abuse of our platforms may harm our reputation or user engagement.',
    'Our products and services, how they are used by customers, and how third-party products and services interact with them',
    'Issues in the development and use of AI may result in reputational or competitive harm or liability.',
    'We may have excessive outages, data losses, and disruptions of our online services',
    'We may experience quality or supply problems.',
    'Government enforcement under competition laws and new market regulation may limit how we design and market our products.',
    'Laws and regulations relating to anti-corruption and trade could result in increased costs',
    'Laws and regulations relating to the handling of personal data may impede the adoption of our services',
    'Existing and increasing legal and regulatory requirements could adversely affect our results of operations.',
    'We have claims and lawsuits against us that may result in adverse outcomes.',
    'Our business with government customers may present additional uncertainties.',
    'We may have additional tax liabilities.',
    'We are subject to evolving sustainability regulatory requirements and expectations',
    'We face risks related to the protection and utilization of our intellectual property',
    'Third parties may claim that we infringe their intellectual property.',
    'If our reputation or our brands are damaged, our business and results of operations may be harmed.',
    'Adverse economic or market conditions may harm our business.',
    'Catastrophic events or geopolitical conditions may disrupt our business.',
    'The occurrence of regional epidemics or a global pandemic, such as COVID-19',
    'Our global business exposes us to operational and economic risks.',
    'Our business depends on our ability to attract and retain talented employees.',
  ],
  'NVDA_10K_2023Q1_2023-02-24': [
    'Failure to meet the evolving needs of our industry and markets may adversely impact our financial results.',
    'Competition in our current and target markets could cause us to lose market share and revenue.',
    'Failure to estimate customer demand properly has led and could lead to mismatches between supply and demand.',
    'Dependency on third-party suppliers and their technology to manufacture, assemble, test, package or design our products',
    'Defects in our products have caused and could cause us to incur significant expenses to remediate, which can damage',
    'Adverse economic conditions may harm our business.',
    'International operations are a significant part of our business, which exposes us',
    'Product, system security, and data protection breaches, as well as cyber-attacks',
    'Business disruptions could harm our operations, lead to a decline in revenue and increase our costs.',
    'Climate change may have a long-term impact on our business.',
    'We may not be able to realize the potential benefits of business investments or acquisitions',
    'We receive a significant amount of our revenue from a limited number of customers and our revenue could be adversely affected',
    'If we are unable to attract, retain and motivate our executives and key employees, our business may be harmed.',
    'Our business is dependent upon the proper functioning of our business processes and information systems',
    'The COVID-19 pandemic has affected and could continue to have a material adverse impact',
    'Our operating results have in the past fluctuated and may in the future fluctuate',
    'Our operations could be affected by the complex laws, rules and regulations to which our business is subject',
    'Increased scrutiny from shareholders, regulators and others regarding our environmental, social and governance responsibilities',
    'Issues relating to the responsible use of our technologies, including AI in our offerings',
    'Actions to adequately protect our IP rights could result in substantial costs to us',
    'We are subject to stringent and changing data privacy and security laws, rules, regulations, and other obligations.',
    'We have exposure to additional tax liabilities',
    'Our business is exposed to the risks associated with litigation, investigations and regulatory proceedings.',
    'Our indebtedness could adversely affect our financial position',
    'Delaware law and our certificate of incorporation, bylaws and agreement with Microsoft could delay or prevent a change in control.',
  ],
  'NVDA_10K_2024Q1_2024-02-21': [
    'Failure to meet the evolving needs of our industry and markets may adversely impact our financial results.',
    'Competition could adversely impact our market share and financial results.',
    'Failure to estimate customer demand accurately has led and could lead to mismatches between supply and demand.',
    'Dependency on third-party suppliers and their technology to manufacture, assemble, test, or package our products',
    'Defects in our products have caused and could cause us to incur significant expenses to remediate, which can damage',
    'Adverse economic conditions may harm our business.',
    'International sales and operations are a significant part of our business, which exposes us',
    'Product, system security, and data protection breaches, as well as cyber-attacks',
    'Business disruptions could harm our operations, lead to a decline in revenue and increase our costs.',
    'Climate change may have a long-term impact on our business.',
    'We may not be able to realize the potential benefits of business investments or acquisitions',
    'We receive a significant amount of our revenue from a limited number of partners and distributors',
    'If we are unable to attract, retain and motivate our executives and key employees, our business may be harmed.',
    'Our business is dependent upon the proper functioning of our business processes and information systems',
    'Our operating results have in the past fluctuated and may in the future fluctuate',
    'Our operations could be affected by the complex laws, rules and regulations to which our business is subject',
    'Increased scrutiny from shareholders, regulators and others regarding our corporate sustainability practices',
    'Issues relating to the responsible use of our technologies, including AI in our offerings',
    'Actions to adequately protect our IP rights could result in substantial costs to us',
    'We are subject to stringent and changing data privacy and security laws, rules, regulations and other obligations.',
    'We may have exposure to additional tax liabilities',
    'Our business is exposed to the risks associated with litigation, investigations and regulatory proceedings.',
    'Our indebtedness could adversely affect our financial position',
    'Delaware law and our certificate of incorporation, bylaws and agreement with Microsoft could delay or prevent a change in control.',
  ],
};

export const SIGNAL_LABELS: readonly FilingPairLabels[] = [
  {
    ticker: 'AAPL',
    earlierDocumentId: 'AAPL_10K_2023Q3_2023-11-03',
    earlierFiscalLabel: 'FY2023',
    laterDocumentId: 'AAPL_10K_2024Q3_2024-11-01',
    laterFiscalLabel: 'FY2024',
    laterHeadings: [
      { later: 'The Company’s operations and performance depend significantly on global and regional economic conditions', earlier: 'The Company’s operations and performance depend significantly on global and regional economic conditions' },
      { later: 'The Company’s business can be impacted by political events, trade and other international disputes, geopolitical tensions', earlier: 'The Company’s business can be impacted by political events, trade and other international disputes, war, terrorism', note: 'Reworded: "war" became "geopolitical tensions, conflict".' },
      { later: 'Global markets for the Company’s products and services are highly competitive', earlier: 'Global markets for the Company’s products and services are highly competitive' },
      { later: 'To remain competitive and stimulate customer demand, the Company must successfully manage frequent introductions', earlier: 'To remain competitive and stimulate customer demand, the Company must successfully manage frequent introductions' },
      { later: 'The Company depends on component and product manufacturing and logistical services', earlier: 'The Company depends on component and product manufacturing and logistical services' },
      { later: 'Future operating results depend upon the Company’s ability to obtain components', earlier: 'Future operating results depend upon the Company’s ability to obtain components' },
      { later: 'The Company’s products and services may be affected from time to time by design and manufacturing defects', earlier: 'The Company’s products and services may be affected from time to time by design and manufacturing defects' },
      { later: 'The Company is exposed to the risk of write-downs on the value of its inventory', earlier: 'The Company is exposed to the risk of write-downs on the value of its inventory' },
      { later: 'The Company relies on access to third-party intellectual property', earlier: 'The Company relies on access to third-party intellectual property' },
      { later: 'The Company’s future performance depends in part on support from third-party software developers.', earlier: 'The Company’s future performance depends in part on support from third-party software developers.' },
      { later: 'Failure to obtain or create digital content that appeals to the Company’s customers', earlier: 'Failure to obtain or create digital content that appeals to the Company’s customers' },
      { later: 'The Company’s success depends largely on the talents and efforts of its team members', earlier: 'The Company’s success depends largely on the talents and efforts of its team members' },
      { later: 'The Company depends on the performance of carriers, wholesalers, retailers and other resellers.', earlier: 'The Company depends on the performance of carriers, wholesalers, retailers and other resellers.' },
      { later: 'The Company’s business and reputation are impacted by information technology system failures', earlier: 'The Company’s business and reputation are impacted by information technology system failures' },
      { later: 'Losses or unauthorized access to or releases of confidential information', earlier: 'Losses or unauthorized access to or releases of confidential information' },
      { later: 'Investment in new business strategies and acquisitions could disrupt', earlier: 'Investment in new business strategies and acquisitions could disrupt' },
      { later: 'The Company’s retail stores are subject to numerous risks and uncertainties.', earlier: 'The Company’s retail stores are subject to numerous risks and uncertainties.' },
      { later: 'The Company’s business, results of operations and financial condition could be adversely impacted by unfavorable results of legal proceedings', earlier: 'The Company’s business, results of operations and financial condition could be adversely impacted by unfavorable results of legal proceedings' },
      { later: 'The Company is subject to complex and changing laws and regulations worldwide', earlier: 'The Company is subject to complex and changing laws and regulations worldwide' },
      { later: 'Expectations relating to environmental, social and governance considerations', earlier: 'Expectations relating to environmental, social and governance considerations' },
      { later: 'The technology industry, including, in some instances, the Company, is subject to intense media, political and regulatory scrutiny', earlier: 'The technology industry, including, in some instances, the Company, is subject to intense media, political and regulatory scrutiny' },
      { later: 'The Company’s business is subject to a variety of U.S. and international laws, rules, policies and other obligations', earlier: 'The Company’s business is subject to a variety of U.S. and international laws, rules, policies and other obligations' },
      { later: 'The Company expects its quarterly net sales and results of operations to fluctuate.', earlier: 'The Company expects its quarterly net sales and results of operations to fluctuate.' },
      { later: 'The Company’s financial performance is subject to risks associated with changes in the value of the U.S. dollar', earlier: 'The Company’s financial performance is subject to risks associated with changes in the value of the U.S. dollar' },
      { later: 'The Company is exposed to credit risk and fluctuations in the values of its investment portfolio.', earlier: 'The Company is exposed to credit risk and fluctuations in the values of its investment portfolio.' },
      { later: 'The Company is exposed to credit risk on its trade accounts receivable', earlier: 'The Company is exposed to credit risk on its trade accounts receivable' },
      { later: 'The Company is subject to changes in tax rates', earlier: 'The Company is subject to changes in tax rates' },
      { later: 'The price of the Company’s stock is subject to volatility.', earlier: 'The price of the Company’s stock is subject to volatility.' },
    ],
    removed: [],
    emphasis: {
      regulatory: { label: 'expanded', why: 'The regulatory-scrutiny risk adds a detailed DMA paragraph (iOS/App Store/Safari changes in the EU, the Commission challenging the compliance plan, DMA fines) and U.S. civil antitrust monopolization suits; the complex-laws risk adds AI-related legal and regulatory considerations.' },
      competition: { label: 'similar', why: 'Competition risk text is essentially unchanged.' },
      supply_chain: { label: 'similar', why: 'Outsourcing and component risks are unchanged apart from small edits ("Changes or additions to the supply chain…" moved into the outsourcing body; one sentence on concentrated supply chains and geopolitical conflict).' },
      cybersecurity: { label: 'similar', why: 'Confidential-information and IT-failure risks have only wording edits (e.g. "armed conflict" became "geopolitical tensions or conflict").' },
      litigation: { label: 'similar', why: 'The legal-proceedings risk is unchanged except one dropped cross-reference sentence; the new U.S. antitrust suits are counted under regulatory.' },
      geographic_concentration: { label: 'similar', why: 'Trade-restriction paragraph is lightly reworded (adds tariffs raising component and raw-material costs) with no material change in China/Asia exposure discussion.' },
      customer_concentration: { label: 'similar', why: 'Carrier/reseller and trade-receivable concentration risks are unchanged.' },
      liquidity_debt: { label: 'similar', why: 'Investment-portfolio and credit-risk sections are unchanged apart from dates.' },
      mda_demand: { label: 'similar', why: 'Segment and product commentary changes from FY2023 declines to FY2024 mixed growth, but there is no new demand outlook discussion.' },
      mda_investment: { label: 'similar', why: 'R&D and capital-return discussion follows the same pattern (new $110B buyback replaces the $90B one); no new capital-spending narrative.' },
      mda_headwinds: { label: 'similar', why: 'Mixed: the repeated FY2023 statements that FX weakness accounted for entire regional declines shrink to brief FX mentions, while a one-time $10.2B State Aid tax charge is added.' },
    },
  },
  {
    ticker: 'AAPL',
    earlierDocumentId: 'AAPL_10K_2024Q3_2024-11-01',
    earlierFiscalLabel: 'FY2024',
    laterDocumentId: 'AAPL_10K_2025-10-31',
    laterFiscalLabel: 'FY2025',
    laterHeadings: [
      { later: 'The Company’s operations and performance depend significantly on global and regional economic conditions', earlier: 'The Company’s operations and performance depend significantly on global and regional economic conditions' },
      { later: 'The Company’s business can be impacted by political events, trade and other international disputes', earlier: 'The Company’s business can be impacted by political events, trade and other international disputes, geopolitical tensions' },
      { later: 'Global markets for the Company’s products and services are highly competitive', earlier: 'Global markets for the Company’s products and services are highly competitive' },
      { later: 'To remain competitive and stimulate customer demand, the Company must successfully manage frequent introductions', earlier: 'To remain competitive and stimulate customer demand, the Company must successfully manage frequent introductions' },
      { later: 'The Company depends on component and product manufacturing and logistical services', earlier: 'The Company depends on component and product manufacturing and logistical services' },
      { later: 'Future operating results depend upon the Company’s ability to obtain components', earlier: 'Future operating results depend upon the Company’s ability to obtain components' },
      { later: 'The Company’s products and services may be affected from time to time by design and manufacturing defects', earlier: 'The Company’s products and services may be affected from time to time by design and manufacturing defects' },
      { later: 'The Company is exposed to the risk of write-downs on the value of its inventory', earlier: 'The Company is exposed to the risk of write-downs on the value of its inventory' },
      { later: 'The Company relies on access to third-party intellectual property', earlier: 'The Company relies on access to third-party intellectual property' },
      { later: 'The Company’s future performance depends in part on support from third-party software developers.', earlier: 'The Company’s future performance depends in part on support from third-party software developers.' },
      { later: 'Failure to obtain or create digital content that appeals to the Company’s customers', earlier: 'Failure to obtain or create digital content that appeals to the Company’s customers' },
      { later: 'The Company’s success depends largely on the talents and efforts of its team members', earlier: 'The Company’s success depends largely on the talents and efforts of its team members' },
      { later: 'The Company depends on the performance of carriers and other resellers.', earlier: 'The Company depends on the performance of carriers, wholesalers, retailers and other resellers.', note: 'Reworded: "carriers, wholesalers, retailers and other resellers" became "carriers and other resellers".' },
      { later: 'The Company’s business and reputation are impacted by information technology system failures', earlier: 'The Company’s business and reputation are impacted by information technology system failures' },
      { later: 'Losses or unauthorized access to or releases of confidential information', earlier: 'Losses or unauthorized access to or releases of confidential information' },
      { later: 'Investment in new business strategies, commercial relationships and acquisitions', earlier: 'Investment in new business strategies and acquisitions could disrupt', note: 'Reworded: adds "commercial relationships".' },
      { later: 'The Company’s business, results of operations and financial condition could be adversely impacted by unfavorable results of legal proceedings', earlier: 'The Company’s business, results of operations and financial condition could be adversely impacted by unfavorable results of legal proceedings' },
      { later: 'The Company is subject to complex and changing laws and regulations worldwide', earlier: 'The Company is subject to complex and changing laws and regulations worldwide' },
      { later: 'Varied stakeholder expectations about social and other issues', earlier: 'Expectations relating to environmental, social and governance considerations', note: 'Reworded: the ESG-expectations risk became "varied stakeholder expectations about social and other issues".' },
      { later: 'The technology industry, including, in some instances, the Company, is subject to intense media, political and regulatory scrutiny', earlier: 'The technology industry, including, in some instances, the Company, is subject to intense media, political and regulatory scrutiny' },
      { later: 'The Company’s business is subject to a variety of U.S. and international laws, rules, policies and other obligations', earlier: 'The Company’s business is subject to a variety of U.S. and international laws, rules, policies and other obligations' },
      { later: 'The Company’s net sales and gross margins are subject to volatility', earlier: 'The Company expects its quarterly net sales and results of operations to fluctuate.', note: 'Reworded: "expects its quarterly net sales and results of operations to fluctuate" became "net sales and gross margins are subject to volatility"; same margin/seasonality body.' },
      { later: 'The Company’s financial performance is subject to risks associated with changes in the value of the U.S. dollar', earlier: 'The Company’s financial performance is subject to risks associated with changes in the value of the U.S. dollar' },
      { later: 'The Company is exposed to credit risk and fluctuations in the values of its investment portfolio.', earlier: 'The Company is exposed to credit risk and fluctuations in the values of its investment portfolio.' },
      { later: 'The Company is exposed to credit risk on its trade accounts receivable', earlier: 'The Company is exposed to credit risk on its trade accounts receivable' },
      { later: 'The Company is subject to changes in tax rates', earlier: 'The Company is subject to changes in tax rates' },
      { later: 'The price of the Company’s stock is subject to volatility.', earlier: 'The price of the Company’s stock is subject to volatility.' },
    ],
    removed: ['The Company’s retail stores are subject to numerous risks and uncertainties.'],
    emphasis: {
      regulatory: { label: 'expanded', why: 'Adds a new paragraph on online-safety laws (protections for minors, mandatory age verification), "executive orders, directives, and enforcement priorities" language, a generalized paragraph on competition-related digital-market laws, the court order barring App Store commissions on certain purchases, and detailed Google search-remedies risk.' },
      competition: { label: 'similar', why: 'Competition risk is restructured (adds wearables and IP-enforcement sentences) but similar in length and substance.' },
      supply_chain: { label: 'similar', why: 'Outsourcing and component risks are similar (component-shortage paragraph is shorter); tariff effects on supply chain are counted under geographic_concentration.' },
      cybersecurity: { label: 'similar', why: 'Confidential-information risk is similar in length with minor rewording.' },
      litigation: { label: 'similar', why: 'Legal-proceedings risk adds AI-related IP claim and settlement-agreement sentences, a modest change.' },
      geographic_concentration: { label: 'expanded', why: 'The trade-restriction paragraph nearly doubles (about 1,950 to 3,650 characters): new U.S. tariffs on imports from China, India, Japan, South Korea, Taiwan, Vietnam and the EU, retaliatory tariffs, the Section 232 semiconductor investigation and rare-earth costs.' },
      customer_concentration: { label: 'similar', why: 'Carrier/reseller risk is shortened slightly; trade-receivable concentration text unchanged.' },
      liquidity_debt: { label: 'similar', why: 'Investment-portfolio and credit-risk sections are unchanged.' },
      mda_demand: { label: 'similar', why: 'Product and segment commentary keeps the same structure with no new demand outlook.' },
      mda_investment: { label: 'similar', why: 'No new capital-spending discussion; buyback and dividend pattern unchanged ($100B program).' },
      mda_headwinds: { label: 'expanded', why: 'A new "Tariffs and Other Measures" section describes the 2025 U.S. tariffs and retaliation, and the Products gross-margin decline is attributed partly to tariff costs.' },
    },
  },
  {
    ticker: 'MSFT',
    earlierDocumentId: 'MSFT_10K_2023Q2_2023-07-27',
    earlierFiscalLabel: 'FY2023',
    laterDocumentId: 'MSFT_10K_2024Q2_2024-07-30',
    laterFiscalLabel: 'FY2024',
    laterHeadings: [
      { later: 'We face intense competition across all markets for our products and services, which may adversely affect our results of operations.', earlier: 'We face intense competition across all markets for our products and services, which may lead to lower revenue', note: 'Reworded tail: "may lead to lower revenue or operating margins" became "may adversely affect our results of operations".' },
      { later: 'Our focus on cloud-based and AI services presents execution and competitive risks.', earlier: 'Our increasing focus on cloud-based services presents execution and competitive risks.', note: 'Reworded and broadened: "increasing focus on cloud-based services" became "focus on cloud-based and AI services".' },
      { later: 'We make significant investments in products and services that may not achieve expected returns.', earlier: 'We make significant investments in products and services that may not achieve expected returns.' },
      { later: 'Acquisitions, joint ventures, and strategic alliances may have an adverse effect on our business.', earlier: 'Acquisitions, joint ventures, and strategic alliances may have an adverse effect on our business.' },
      { later: 'If our goodwill or amortizable intangible assets become impaired', earlier: 'If our goodwill or amortizable intangible assets become impaired' },
      { later: 'Cyberattacks and security vulnerabilities could lead to reduced revenue', earlier: 'Cyberattacks and security vulnerabilities could lead to reduced revenue' },
      { later: 'Disclosure and misuse of personal data could result in liability and harm our reputation.', earlier: 'Disclosure and misuse of personal data could result in liability and harm our reputation.' },
      { later: 'We may not be able to protect information in our products and services from use by others.', earlier: 'We may not be able to protect information in our products and services from use by others.' },
      { later: 'Abuse of our platforms may harm our reputation or user engagement.', earlier: 'Abuse of our platforms may harm our reputation or user engagement.' },
      { later: 'Our products and services, how they are used by customers, and how third-party products and services interact with them', earlier: 'The development of the IoT presents security, privacy, and execution risks.', note: 'Reworded and broadened: the FY2023 IoT risk ("The development of the IoT presents security, privacy, and execution risks.") was generalized to all products and services, keeping IoT as an example and adding customer misuse of AI products.' },
      { later: 'Issues in the development and use of AI may result in reputational or competitive harm or liability.', earlier: 'Issues in the development and use of AI may result in reputational or competitive harm or liability.' },
      { later: 'We may have excessive outages, data losses, and disruptions of our online services', earlier: 'We may have excessive outages, data losses, and disruptions of our online services' },
      { later: 'We may experience quality or supply problems.', earlier: 'We may experience quality or supply problems.' },
      { later: 'Government enforcement under competition laws and new market regulation may limit how we design and market our products.', earlier: 'Government litigation and regulatory activity relating to competition rules may limit how we design and market our products.', note: 'Reworded: "Government litigation and regulatory activity relating to competition rules" became "Government enforcement under competition laws and new market regulation" (adds EU DMA designation).' },
      { later: 'Laws and regulations relating to anti-corruption and trade could result in increased costs', earlier: 'Laws and regulations relating to anti-corruption and trade could result in increased costs' },
      { later: 'Laws and regulations relating to the handling of personal data may impede the adoption of our services', earlier: 'Laws and regulations relating to the handling of personal data may impede the adoption of our services' },
      { later: 'Existing and increasing legal and regulatory requirements could adversely affect our results of operations.', earlier: 'Existing and increasing legal and regulatory requirements could adversely affect our results of operations.' },
      { later: 'We have claims and lawsuits against us that may result in adverse outcomes.', earlier: 'We have claims and lawsuits against us that may result in adverse outcomes.' },
      { later: 'Our business with government customers may present additional uncertainties.', earlier: 'Our business with government customers may present additional uncertainties.' },
      { later: 'We may have additional tax liabilities.', earlier: 'We may have additional tax liabilities.' },
      { later: 'We are subject to evolving sustainability regulatory requirements and expectations', earlier: null, note: 'Genuinely new risk factor. Promoted from body: FY2023 mentioned sustainability only in passing in the body of the reputation risk ("our environmental impact and sustainability") and in a climate-change paragraph inside the general-risks group; it had no sustainability-regulation risk factor.' },
      { later: 'We face risks related to the protection and utilization of our intellectual property', earlier: 'We face risks related to the protection and utilization of our intellectual property' },
      { later: 'Third parties may claim that we infringe their intellectual property.', earlier: 'Third parties may claim that we infringe their intellectual property.' },
      { later: 'If our reputation or our brands are damaged, our business and results of operations may be harmed.', earlier: 'If our reputation or our brands are damaged, our business and operating results may be harmed.', note: 'Reworded: "business and operating results" became "business and results of operations".' },
      { later: 'Adverse economic or market conditions may harm our business.', earlier: 'Adverse economic or market conditions may harm our business.' },
      { later: 'Catastrophic events or geopolitical conditions may disrupt our business.', earlier: 'Catastrophic events or geopolitical conditions may disrupt our business.' },
      { later: 'The occurrence of regional epidemics or a global pandemic, such as COVID-19', earlier: 'The occurrence of regional epidemics or a global pandemic, such as COVID-19' },
      { later: 'Our global business exposes us to operational and economic risks.', earlier: 'Our global business exposes us to operational and economic risks.' },
      { later: 'Our business depends on our ability to attract and retain talented employees.', earlier: 'Our business depends on our ability to attract and retain talented employees.' },
    ],
    removed: [],
    emphasis: {
      regulatory: { label: 'expanded', why: 'Adds the EU DMA designation of Windows and LinkedIn, the EU AI Act and U.S. AI executive order as AI-liability sources, expanding law-enforcement data demands, and a new standalone sustainability-regulation risk factor.' },
      competition: { label: 'similar', why: 'Competition risks are lightly reworded; AI and cloud bullets slightly expanded but substance unchanged.' },
      supply_chain: { label: 'similar', why: 'Quality-or-supply risk is reorganized (adds datacenter capacity expansion for AI demand) with similar substance.' },
      cybersecurity: { label: 'expanded', why: 'Cyberattack risk grows from about 13,600 to 16,300 characters with the late-2023 nation-state attack on corporate email and source code, inadequate account-security practices, AI-enabled threat actors, and incident-investigation and insider-threat sentences.' },
      litigation: { label: 'expanded', why: 'New legal exposure is disclosed across risks: the FTC continuing to challenge the Activision Blizzard acquisition, copyright claims over AI training and output, "new and novel legal claims", and IRS NOPAs seeking $28.9B plus penalties and interest.' },
      geographic_concentration: { label: 'similar', why: 'Global-business and geopolitical risks are essentially unchanged.' },
      customer_concentration: { label: 'similar', why: 'No customer-concentration discussion in either year beyond government customers, which is unchanged.' },
      liquidity_debt: { label: 'similar', why: 'Investment-portfolio sentence unchanged; no debt risk factor in either year.' },
      mda_demand: { label: 'similar', why: 'Same outlook language tying demand to macroeconomic and geopolitical factors and growing AI demand.' },
      mda_investment: { label: 'similar', why: 'Same statement that capital expenditures will increase for cloud and AI infrastructure (adds "and training").' },
      mda_headwinds: { label: 'reduced', why: 'FY2023 cited FX reducing reported revenue, the $1.2B Q2 charge with about 10,000 job cuts, and PC demand weakness; FY2024 says FX had no material impact and has no restructuring discussion.' },
    },
  },
  {
    ticker: 'MSFT',
    earlierDocumentId: 'MSFT_10K_2024Q2_2024-07-30',
    earlierFiscalLabel: 'FY2024',
    laterDocumentId: 'MSFT_10K_2025-07-30',
    laterFiscalLabel: 'FY2025',
    laterHeadings: [
      { later: 'We face intense competition across all markets for our products and services', earlier: 'We face intense competition across all markets for our products and services, which may adversely affect our results of operations.' },
      { later: 'Our focus on cloud-based and AI services presents execution and competitive risks.', earlier: 'Our focus on cloud-based and AI services presents execution and competitive risks.' },
      { later: 'We make significant investments in products and services that may not achieve expected returns.', earlier: 'We make significant investments in products and services that may not achieve expected returns.' },
      { later: 'Acquisitions, joint ventures, and strategic alliances could have an adverse effect on our business.', earlier: 'Acquisitions, joint ventures, and strategic alliances may have an adverse effect on our business.', note: 'Reworded ("may have" became "could have"). MERGE: also absorbs the FY2024 goodwill-impairment risk ("If our goodwill or amortizable intangible assets become impaired…"), which is now one sentence of this body.' },
      { later: 'Cyberattacks and security vulnerabilities could lead to reduced revenue', earlier: 'Cyberattacks and security vulnerabilities could lead to reduced revenue' },
      { later: 'Disclosure and misuse of personal data could result in liability and harm our reputation.', earlier: 'Disclosure and misuse of personal data could result in liability and harm our reputation.' },
      { later: 'We may not be able to protect information in our products and services from use by others.', earlier: 'We may not be able to protect information in our products and services from use by others.' },
      { later: 'Abuse of our platforms may harm our reputation or user engagement.', earlier: 'Abuse of our platforms may harm our reputation or user engagement.' },
      { later: 'Our products and services, how they are used by customers, and how third-party products and services interact with them', earlier: 'Our products and services, how they are used by customers, and how third-party products and services interact with them' },
      { later: 'Issues in the development, deployment, and use of AI may result in reputational or competitive harm or liability.', earlier: 'Issues in the development and use of AI may result in reputational or competitive harm or liability.', note: 'Reworded: adds "deployment".' },
      { later: 'We may have excessive outages, data losses, and disruptions of our online services', earlier: 'We may have excessive outages, data losses, and disruptions of our online services' },
      { later: 'We may experience supply or quality problems.', earlier: 'We may experience quality or supply problems.', note: 'Reworded: "quality or supply" became "supply or quality".' },
      { later: 'We are subject to a variety of new, existing, and evolving legal and regulatory requirements', earlier: 'Existing and increasing legal and regulatory requirements could adversely affect our results of operations.', note: 'MERGE: one risk factor with bullets (competition laws and new market regulation, AI, anti-corruption, trade, cybersecurity, handling of personal data, ESG) replaces five FY2024 risk factors: "Existing and increasing legal and regulatory requirements…" (mapped here as the closest), "Government enforcement under competition laws…", "Laws and regulations relating to anti-corruption and trade…", "Laws and regulations relating to the handling of personal data…", and "We are subject to evolving sustainability regulatory requirements…". The AI and cybersecurity-regulation bullets are new content.' },
      { later: 'We have claims and lawsuits against us that may result in adverse outcomes.', earlier: 'We have claims and lawsuits against us that may result in adverse outcomes.' },
      { later: 'Our business with government customers may present additional uncertainties.', earlier: 'Our business with government customers may present additional uncertainties.' },
      { later: 'We may have additional tax liabilities.', earlier: 'We may have additional tax liabilities.' },
      { later: 'We face risks related to the protection and utilization of our intellectual property', earlier: 'We face risks related to the protection and utilization of our intellectual property' },
      { later: 'Third parties may claim that we infringe their intellectual property.', earlier: 'Third parties may claim that we infringe their intellectual property.' },
      { later: 'If our reputation or our brands are damaged, our business and results of operations may be harmed.', earlier: 'If our reputation or our brands are damaged, our business and results of operations may be harmed.' },
      { later: 'Adverse economic or market conditions could harm our business.', earlier: 'Adverse economic or market conditions may harm our business.', note: 'Reworded: "may harm" became "could harm".' },
      { later: 'Catastrophic events or geopolitical conditions could disrupt our business.', earlier: 'Catastrophic events or geopolitical conditions may disrupt our business.', note: 'Reworded: "may disrupt" became "could disrupt".' },
      { later: 'The occurrence of regional epidemics or a global pandemic, such as COVID-19', earlier: 'The occurrence of regional epidemics or a global pandemic, such as COVID-19' },
      { later: 'Our global business exposes us to operational and economic risks.', earlier: 'Our global business exposes us to operational and economic risks.' },
      { later: 'Our business depends on our ability to attract and retain talented employees.', earlier: 'Our business depends on our ability to attract and retain talented employees.' },
    ],
    removed: [],
    emphasis: {
      regulatory: { label: 'similar', why: 'Restructured rather than de-emphasized: five FY2024 legal and regulatory risk factors are merged into one bulleted risk (about 14,400 to 9,200 characters, trimming GDPR, DPF and competition detail), but new AI-regulation, AI Diffusion Rule/tariff and cybersecurity-regulation bullets are added.' },
      competition: { label: 'similar', why: 'Competition risk text largely unchanged.' },
      supply_chain: { label: 'similar', why: 'Supply-or-quality risk similar; one sentence on tariff volatility affecting cloud and devices supply-chain costs.' },
      cybersecurity: { label: 'similar', why: 'Similar length (about 16,300 to 16,700 characters): patching and development-process weaknesses added, follow-up detail on the nation-state incident trimmed.' },
      litigation: { label: 'similar', why: 'Claims-and-lawsuits risk unchanged; FTC/Activision sentence dropped.' },
      geographic_concentration: { label: 'similar', why: 'Global-business risk unchanged; trade/tariff language is counted under regulatory.' },
      customer_concentration: { label: 'similar', why: 'No customer-concentration discussion change.' },
      liquidity_debt: { label: 'similar', why: 'Unchanged.' },
      mda_demand: { label: 'similar', why: 'Same demand outlook language; Azure growth attributed to demand.' },
      mda_investment: { label: 'expanded', why: 'Adds a section on the OpenAI partnership and investment, and attributes gross-margin declines in Microsoft Cloud and segments to scaling AI infrastructure and opex growth to cloud and AI engineering.' },
      mda_headwinds: { label: 'expanded', why: 'Adds a new statement that trade-policy changes including tariffs could increase supply-chain challenges and cost volatility, and Microsoft Cloud gross margin falls to 69% on AI infrastructure scaling.' },
    },
  },
  {
    ticker: 'NVDA',
    earlierDocumentId: 'NVDA_10K_2023Q1_2023-02-24',
    earlierFiscalLabel: 'FY2023',
    laterDocumentId: 'NVDA_10K_2024Q1_2024-02-21',
    laterFiscalLabel: 'FY2024',
    laterHeadings: [
      { later: 'Failure to meet the evolving needs of our industry and markets may adversely impact our financial results.', earlier: 'Failure to meet the evolving needs of our industry and markets may adversely impact our financial results.' },
      { later: 'Competition could adversely impact our market share and financial results.', earlier: 'Competition in our current and target markets could cause us to lose market share and revenue.', note: 'Reworded: "Competition in our current and target markets could cause us to lose market share and revenue." became "Competition could adversely impact our market share and financial results."' },
      { later: 'Failure to estimate customer demand accurately has led and could lead to mismatches between supply and demand.', earlier: 'Failure to estimate customer demand properly has led and could lead to mismatches between supply and demand.', note: 'Reworded: "properly" became "accurately".' },
      { later: 'Dependency on third-party suppliers and their technology to manufacture, assemble, test, or package our products', earlier: 'Dependency on third-party suppliers and their technology to manufacture, assemble, test, package or design our products', note: 'Reworded: drops "or design".' },
      { later: 'Defects in our products have caused and could cause us to incur significant expenses to remediate, which can damage', earlier: 'Defects in our products have caused and could cause us to incur significant expenses to remediate, which can damage' },
      { later: 'Adverse economic conditions may harm our business.', earlier: 'Adverse economic conditions may harm our business.' },
      { later: 'International sales and operations are a significant part of our business, which exposes us', earlier: 'International operations are a significant part of our business, which exposes us', note: 'Reworded: "International operations" became "International sales and operations".' },
      { later: 'Product, system security, and data protection breaches, as well as cyber-attacks', earlier: 'Product, system security, and data protection breaches, as well as cyber-attacks' },
      { later: 'Business disruptions could harm our operations, lead to a decline in revenue and increase our costs.', earlier: 'Business disruptions could harm our operations, lead to a decline in revenue and increase our costs.' },
      { later: 'Climate change may have a long-term impact on our business.', earlier: 'Climate change may have a long-term impact on our business.' },
      { later: 'We may not be able to realize the potential benefits of business investments or acquisitions', earlier: 'We may not be able to realize the potential benefits of business investments or acquisitions' },
      { later: 'We receive a significant amount of our revenue from a limited number of partners and distributors', earlier: 'We receive a significant amount of our revenue from a limited number of customers and our revenue could be adversely affected', note: 'Reworded: "limited number of customers" became "limited number of partners and distributors" plus a concentration of direct and indirect end-customer sales (Customer A 13%, an indirect customer ~19%).' },
      { later: 'If we are unable to attract, retain and motivate our executives and key employees, our business may be harmed.', earlier: 'If we are unable to attract, retain and motivate our executives and key employees, our business may be harmed.' },
      { later: 'Our business is dependent upon the proper functioning of our business processes and information systems', earlier: 'Our business is dependent upon the proper functioning of our business processes and information systems' },
      { later: 'Our operating results have in the past fluctuated and may in the future fluctuate', earlier: 'Our operating results have in the past fluctuated and may in the future fluctuate' },
      { later: 'Our operations could be affected by the complex laws, rules and regulations to which our business is subject', earlier: 'Our operations could be affected by the complex laws, rules and regulations to which our business is subject' },
      { later: 'Increased scrutiny from shareholders, regulators and others regarding our corporate sustainability practices', earlier: 'Increased scrutiny from shareholders, regulators and others regarding our environmental, social and governance responsibilities', note: 'Reworded: "environmental, social and governance responsibilities" became "corporate sustainability practices".' },
      { later: 'Issues relating to the responsible use of our technologies, including AI in our offerings', earlier: 'Issues relating to the responsible use of our technologies, including AI in our offerings' },
      { later: 'Actions to adequately protect our IP rights could result in substantial costs to us', earlier: 'Actions to adequately protect our IP rights could result in substantial costs to us' },
      { later: 'We are subject to stringent and changing data privacy and security laws, rules, regulations and other obligations.', earlier: 'We are subject to stringent and changing data privacy and security laws, rules, regulations, and other obligations.', note: 'Same heading; a comma before "and other obligations" was dropped.' },
      { later: 'We may have exposure to additional tax liabilities', earlier: 'We have exposure to additional tax liabilities', note: 'Reworded: "We have exposure" became "We may have exposure".' },
      { later: 'Our business is exposed to the risks associated with litigation, investigations and regulatory proceedings.', earlier: 'Our business is exposed to the risks associated with litigation, investigations and regulatory proceedings.' },
      { later: 'Our indebtedness could adversely affect our financial position', earlier: 'Our indebtedness could adversely affect our financial position' },
      { later: 'Delaware law and our certificate of incorporation, bylaws and agreement with Microsoft could delay or prevent a change in control.', earlier: 'Delaware law and our certificate of incorporation, bylaws and agreement with Microsoft could delay or prevent a change in control.' },
    ],
    removed: ['The COVID-19 pandemic has affected and could continue to have a material adverse impact'],
    emphasis: {
      regulatory: { label: 'expanded', why: 'The laws-and-regulations risk roughly doubles (about 9,800 to 19,500 characters): October 2023 export licensing for A100/H100/L40S and D1/D4/D5 countries, regulator inquiries in the EU, UK, China and France, and proposed AI and frontier-model regulation.' },
      competition: { label: 'similar', why: 'Competition risk unchanged in length and substance.' },
      supply_chain: { label: 'expanded', why: 'Demand/supply risk grows from about 10,700 to 13,700 characters with increased supply and capacity purchases, prepaid capacity agreements, new vendors, expected supply-constrained next-generation products; adds Taiwan supply dependence and Hong Kong distribution exposure.' },
      cybersecurity: { label: 'expanded', why: 'Security risk grows from about 5,500 to 7,700 characters with AI-enabled attacks, insider and third-party failures, past incidents from mishandled information and notification obligations.' },
      litigation: { label: 'similar', why: 'Litigation risk unchanged.' },
      geographic_concentration: { label: 'expanded', why: 'Adds China falling from 19% to 14% of Data Center revenue under export controls, operations moved out of China and Hong Kong, Taiwan supply dependence, and the Israel–Hamas conflict with employees called to military duty.' },
      customer_concentration: { label: 'expanded', why: 'Concentration risk now names Customer A at 13% of revenue and an indirect customer at about 19% (about 1,600 to 2,600 characters).' },
      liquidity_debt: { label: 'similar', why: 'Indebtedness risk unchanged; investment-portfolio sentences added to adverse-economic risk are minor.' },
      mda_demand: { label: 'expanded', why: 'FY2023 discussed weak gaming demand and channel inventory reduction; FY2024 says data center demand surged, remains very strong, and next-generation products will be supply-constrained.' },
      mda_investment: { label: 'similar', why: 'Both years discuss growing supply, purchase obligations and prepaid supply/capacity agreements; no new capital-spending narrative.' },
      mda_headwinds: { label: 'similar', why: 'Headwinds shift rather than grow: FY2023 inventory charges ($2.17B), Arm termination charge and COVID lockdowns are replaced by October 2023 export controls, macro factors and the Israel–Hamas conflict.' },
    },
  },
  {
    ticker: 'NVDA',
    earlierDocumentId: 'NVDA_10K_2024Q1_2024-02-21',
    earlierFiscalLabel: 'FY2024',
    laterDocumentId: 'NVDA_10K_2025-02-26',
    laterFiscalLabel: 'FY2025',
    laterHeadings: [
      { later: 'Failure to meet the evolving needs of our industry and markets may adversely impact our financial results.', earlier: 'Failure to meet the evolving needs of our industry and markets may adversely impact our financial results.' },
      { later: 'Competition could adversely impact our market share and financial results.', earlier: 'Competition could adversely impact our market share and financial results.' },
      { later: 'Long manufacturing lead times and uncertain supply and component availability', earlier: 'Failure to estimate customer demand accurately has led and could lead to mismatches between supply and demand.', note: 'Reworded: the demand-estimation risk now leads with "Long manufacturing lead times and uncertain supply and component availability, combined with a failure to estimate customer demand accurately".' },
      { later: 'Dependency on third-party suppliers and their technology to manufacture, assemble, test, or package our products', earlier: 'Dependency on third-party suppliers and their technology to manufacture, assemble, test, or package our products' },
      { later: 'Defects in our products have caused and could cause us to incur significant expenses to remediate', earlier: 'Defects in our products have caused and could cause us to incur significant expenses to remediate, which can damage' },
      { later: 'Adverse economic conditions may harm our business.', earlier: 'Adverse economic conditions may harm our business.' },
      { later: 'International sales and operations are a significant part of our business', earlier: 'International sales and operations are a significant part of our business, which exposes us' },
      { later: 'Product, system security, and data protection incidents or breaches', earlier: 'Product, system security, and data protection breaches, as well as cyber-attacks', note: 'Reworded: "breaches, as well as cyber-attacks" became "incidents or breaches".' },
      { later: 'Business disruptions could harm our operations, lead to a decline in revenue and increase our costs.', earlier: 'Business disruptions could harm our operations, lead to a decline in revenue and increase our costs.' },
      { later: 'Climate change may have a long-term impact on our business.', earlier: 'Climate change may have a long-term impact on our business.' },
      { later: 'We may not be able to realize the potential benefits of business investments or acquisitions', earlier: 'We may not be able to realize the potential benefits of business investments or acquisitions' },
      { later: 'We receive a significant amount of our revenue from a limited number of partners and distributors', earlier: 'We receive a significant amount of our revenue from a limited number of partners and distributors' },
      { later: 'If we are unable to attract, retain and motivate our executives and key employees, our business may be harmed.', earlier: 'If we are unable to attract, retain and motivate our executives and key employees, our business may be harmed.' },
      { later: 'Our business is dependent upon the proper functioning of our business processes and information systems', earlier: 'Our business is dependent upon the proper functioning of our business processes and information systems' },
      { later: 'Our operating results have in the past fluctuated and may in the future fluctuate', earlier: 'Our operating results have in the past fluctuated and may in the future fluctuate' },
      { later: 'We are subject to complex laws, rules, regulations, and political and other actions', earlier: 'Our operations could be affected by the complex laws, rules and regulations to which our business is subject', note: 'Reworded: "Our operations could be affected by the complex laws, rules and regulations…" became "We are subject to complex laws, rules, regulations, and political and other actions…".' },
      { later: 'Increased scrutiny from shareholders, regulators and others regarding our corporate sustainability practices', earlier: 'Increased scrutiny from shareholders, regulators and others regarding our corporate sustainability practices' },
      { later: 'Issues relating to the responsible use of our technologies, including AI in our offerings', earlier: 'Issues relating to the responsible use of our technologies, including AI in our offerings' },
      { later: 'Actions to adequately protect our IP rights could result in substantial costs to us', earlier: 'Actions to adequately protect our IP rights could result in substantial costs to us' },
      { later: 'We are subject to stringent and changing data privacy and security laws, rules, regulations and other obligations.', earlier: 'We are subject to stringent and changing data privacy and security laws, rules, regulations and other obligations.' },
      { later: 'We may have exposure to additional tax liabilities', earlier: 'We may have exposure to additional tax liabilities' },
      { later: 'Our business is exposed to the burden and risks associated with litigation, investigations and regulatory proceedings.', earlier: 'Our business is exposed to the risks associated with litigation, investigations and regulatory proceedings.', note: 'Reworded: adds "the burden and".' },
      { later: 'Delaware law and our certificate of incorporation, bylaws and agreement with Microsoft could delay or prevent a change in control.', earlier: 'Delaware law and our certificate of incorporation, bylaws and agreement with Microsoft could delay or prevent a change in control.' },
    ],
    removed: ['Our indebtedness could adversely affect our financial position'],
    emphasis: {
      regulatory: { label: 'expanded', why: 'The laws-and-regulations risk grows from about 19,500 to 26,300 characters with the AI Diffusion IFR (worldwide licensing, country tiers), Blackwell licensing, China’s investigation and Action Plan, the EU AI Act, state AI laws, and NIS2.' },
      competition: { label: 'similar', why: 'Competition risk unchanged apart from a sentence on the competitive China market.' },
      supply_chain: { label: 'similar', why: 'Demand/supply risk is rewritten and somewhat shorter (about 13,700 to 10,800 characters; adds annual product cadence and low-yield Blackwell provisions, drops FY2024-specific supply notes), with no material change in emphasis.' },
      cybersecurity: { label: 'similar', why: 'Security risk similar (about 7,700 to 8,200 characters).' },
      litigation: { label: 'similar', why: 'Litigation risk unchanged.' },
      geographic_concentration: { label: 'similar', why: 'International risk similar; China-share and Israel detail trimmed while China export-control content is counted under regulatory.' },
      customer_concentration: { label: 'expanded', why: 'Concentration expands from one 13% customer to direct Customers A, B and C at 12%, 11% and 11%, plus a new dependence on a small number of system-integration partners.' },
      liquidity_debt: { label: 'reduced', why: 'The standalone indebtedness risk factor ($9.7B notes, covenants, credit rating) is removed; only a bank-failure sentence is added.' },
      mda_demand: { label: 'similar', why: 'Demand remains described as strong (Hopper, generative AI) with the same estimation caveats.' },
      mda_investment: { label: 'similar', why: 'Same narrative of increasing supply and capacity purchases and prepaid agreements.' },
      mda_headwinds: { label: 'similar', why: 'Blackwell licensing, possible import restrictions and tariffs are added but Israel detail is trimmed and China Data Center revenue grew; no material shift.' },
    },
  },
];
